# Generated by Django 5.2.6 on 2025-09-26 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FormSubmission',
            new_name='Submission',
        ),
    ]
