# Generated by Django 5.2.6 on 2025-09-30 07:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0002_rename_formsubmission_submission'),
    ]

    operations = [
        migrations.CreateModel(
            name='DynamicForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='submission',
            name='email',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='message',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='name',
        ),
        migrations.AddField(
            model_name='submission',
            name='data',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='submission',
            name='form',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='forms.dynamicform'),
        ),
        migrations.CreateModel(
            name='FormField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255)),
                ('field_type', models.CharField(choices=[('text', 'Text'), ('number', 'Number'), ('file', 'File')], max_length=20)),
                ('required', models.BooleanField(default=True)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='forms.dynamicform')),
            ],
        ),
    ]
